# -*- coding: utf-8 -*-
"""Utils/model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sIR7UWAiAPUU6v6z8Tn6cV-XsKCkg0ir
"""

import pickle
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

def train_model(X_train, y_train):
    """Train a logistic regression model with TF-IDF features."""
    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer()),
        ('clf', LogisticRegression(max_iter=1000))
    ])
    pipeline.fit(X_train, y_train)
    return pipeline

def evaluate_model(model, X_test, y_test):
    """Print model evaluation metrics."""
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))

def save_model(model, filepath='models/mental_health_model.pkl'):
    """Save model to a file."""
    with open(filepath, 'wb') as f:
        pickle.dump(model, f)

def load_model(filepath='models/mental_health_model.pkl'):
    """Load model from a file."""
    with open(filepath, 'rb') as f:
        return pickle.load(f)